### ISSUE TITLE
Import Attributes 

### ISSUE THREAD

**Issue by o-az** [whitefusionhq/esbuild-plugin-html-modules#5]
Great plugin. Heads up in 2023-03, the keyword is changed (back) from `assert` to `with`: 
https://github.com/tc39/proposal-import-attributes?tab=readme-ov-file#history

Already integrated in HTML:
https://html.spec.whatwg.org/#hostloadimportedmodule

**Comment by jaredcwhite** [comment]
Thanks @o-az for reminding me, I should update
